---
title: "Temp study"
author: "Andria Constantinou"
date: "02/10/2020"
output: html_document
---


```{r libraries, include=FALSE}
rm(list = ls(all=TRUE))
ipak <- function(pkg){
  new.pkg <- pkg[!(pkg %in% installed.packages()[, "Package"])]
  if (length(new.pkg)) 
    install.packages(new.pkg, dependencies = TRUE)
  sapply(pkg, require, character.only = TRUE)
}

# usage
packages <- c("readxl","quantmod", "pracma", "base", "highcharter", "chron", "dplyr", "reshape2", "tidyr", 
              "tableone", "data.table","plyr","dtplyr","data.table","knitr", "tibble","Hmisc","compare",
              "stargazer", "readr","ggplot2","sjPlot","tidyverse","lubridate","eeptools", "Rcpp", "nlme", 
              "lme4","lmerTest","texreg","reshape","scales","FSA","NADA","psych","corrplot", "xts",
              "dygraphs","webshot", "gsubfn","forcats","nortest","ggpubr","languageR")

ipak(packages)
```

```{r creating the two group vector, include=FALSE}
# Loading the file with the group information
group <- read.csv("Recruitment Management Form-use in R.csv", sep=";")
group <- group[,1:2] # removing anything except code and group
group <- group[-c(15,26,30,39),] # removing this participants
group_1 <- filter(group, Group=="1")
group_2 <- filter(group,Group=="2")

part_g1 <- group_1$Code
part_g2 <- group_2$Code

rm(group, group_1, group_2)
```


```{r loading the dataset,  include=FALSE}
############ READING THE DATA #################

#reading all the data 
# write path for sensors data
path = "D:/MACHINE LEARNING/projects/temp/new/"

# create list of sensors data files
files <- list.files(path, pattern = ".csv")
# read first file of the list
DF <-  read.csv(paste0(path,files[1]), header=T, sep=";")
# add filename as a column in the first sensor data file
DF$FILENAME<-as.character(files[1])

# read each sensor data file and append them to create one file
for (f in files[-1]){
  df <- read.csv(paste0(path,f), header=T, sep=";")      # read the file
  df$FILENAME<-as.character(f)                        # add filename as column
  DF <- rbind(DF, df)                                   # append the current file
}

# fixing entries for T42-S1. He has index for every second and values every 30 sec.
T42_S1 <- DF[DF$FILENAME=="T42_S1new.csv",]
T42_S1 <- T42_S1[!is.na(T42_S1$Temperature),]
T42_S1 <- T42_S1[seq(1,2880,2),]


DF <- DF[DF$FILENAME!="T42_S1new.csv",]


# deleting the 1441st entry 
DF<- DF %>% 
  group_by(FILENAME) %>% 
  slice(1:1440)

DF <- rbind(DF,T42_S1)

# remove rows with no values for temperature
DF <- DF %>%
  filter(!is.na(Temperature)) 

#Seperate the Date variable into 2 other "Date" and "Time"
tempdata1<-tidyr::separate(DF, Date, c("Date", "Time"), sep = "--")

# create Code variable by deleting 7 characters from FILENAME
# FILENAME needs to be character
tempdata1$FILENAME<-as.character(tempdata1$FILENAME)
tempdata1$Code<- substr(tempdata1$FILENAME, 
                        start=1,
                        stop=nchar(tempdata1$FILENAME)-10)

# create order variable by starting from position 6 and deleting 4 characters from FILENAME
tempdata1$order<- substr(tempdata1$FILENAME, 
                         start=5,
                         stop=nchar(tempdata1$FILENAME)-7)

# create temp type variable (air (a) or skin(s)) by starting from position 5 
# and deleting 5 characters from FILENAME
tempdata1$temp_type<- substr(tempdata1$FILENAME, 
                             start=5,
                             stop=nchar(tempdata1$FILENAME)-8)

## create Code_order variable by merging Code and order variables 
tempdata1$Code_order <- paste(tempdata1$Code, tempdata1$order, sep = "-")

# convert Code_order and Code to factors
tempdata1[, c("Code_order", "Code")]<-lapply(
  tempdata1[, c("Code_order", "Code")],
  factor)

# create subset with variables needed only: date, temperature, activity, code_order
tempdata<-subset(tempdata1, select=c(Code, Code_order, order, Date,Time, 
                                     Temperature, temp_type,Activity)) 
rm(tempdata1,DF, df,T42_S1)
```

```{r,include=FALSE}
# we gonna set 1==urban area and 2==rural area
# group 1 participants start from city and then go to mountain

tempdata_1 <- tempdata %>% filter(Code %in% part_g1)
tempdata_1$settings <- ifelse(tempdata_1$order %in% c("A1","S1"),"1","2")
tempdata_1$Group <- "1"

tempdata_2 <- tempdata %>% filter(Code %in% part_g2)
tempdata_2$settings <- ifelse(tempdata_2$order %in% c("A1","S1"),"2","1")
tempdata_2$Group <- "2"

tempdata_final <- rbind(tempdata_1,tempdata_2)
tempdata_final$order <- paste0(tempdata_final$temp_type,tempdata_final$settings)
tempdata_final$Code_order <- paste(tempdata_final$Code, tempdata_final$order, sep = "-")

rm(tempdata_1,tempdata_2,tempdata)
```

```{r reading the data and removing temperature below 34, include=FALSE}
# create a subset with skintemp and airtemp data only
data_skin<-tempdata_final[which(tempdata_final$temp_type == "S"),]
data_air<-tempdata_final[which(tempdata_final$temp_type == "A"),]

data_skin <- subset(data_skin, Temperature>=30)
```


```{r creating the diary and activity diary, include=FALSE}
#reading the diary that includes 4 wide categories (indoor,outdoor, unspecified, indoor_ac)
setwd("D:/MACHINE LEARNING/projects/temp/")
diary<- read.csv("rdiaryfinal.csv", header=T, sep=";", na.strings=c("","NA"))
diary_1 <- diary %>% filter(ID %in% part_g1)
diary_2 <- diary %>% filter(ID %in% part_g2)
diary_2$Setting <- ifelse(diary_2$Setting=="1","2","1")
diary <- rbind(diary_1,diary_2)

# create subsets according to the setting (4 subset skin/air sensors in each setting)
diaryskin_set1<-diary [which(diary$Setting == "1"),]
diaryskin_set2<-diary [which(diary$Setting == "2"),]
diaryair_set1<-diary [which(diary$Setting == "1"),]
diaryair_set2<-diary [which(diary$Setting == "2"),]

# in order to merge the diary to the four different datasets that we will create (one for peaks one for troughs in each setting)
# we create a new variable Code_order by merging the ID col with Setting variables and seperate them 
#by 'S-' for skin data 
diaryskin_set1$Code_order <- paste(diaryskin_set1$ID, diaryskin_set1$Setting, sep = "-S")                 
diaryskin_set2$Code_order <- paste(diaryskin_set2$ID, diaryskin_set2$Setting, sep = "-S")         
diaryair_set1$Code_order <- paste(diaryair_set1$ID, diaryair_set1$Setting, sep = "-A")                 
diaryair_set2$Code_order <- paste(diaryair_set2$ID, diaryair_set2$Setting, sep = "-A")         

#removing the two first columns (ID, Setting) 
diaryair_set1<-select (diaryair_set1, -c(ID, Setting))
diaryair_set2<-select (diaryair_set2, -c(ID, Setting))
diaryskin_set1<-select (diaryskin_set1, -c(ID, Setting))
diaryskin_set2<-select (diaryskin_set2, -c(ID, Setting))

#reading the diary that includes all activities (wake_up, sleep, housekeeping, being_at_work, driving, etc)
diary_activities<- read.csv("diaryfinal.csv", header=T, sep=";", na.strings=c("","NA"))
diary_activities_1 <- diary_activities %>% filter(ID %in% part_g1)
diary_activities_2 <- diary_activities %>% filter(ID %in% part_g2)
diary_activities_2$Setting <- ifelse(diary_activities_2$Setting=="1","2","1")
diary_activities <- rbind(diary_activities_1,diary_activities_2)


# create subsets according to the setting (4 subset skin/air sensors in each setting)
adiaryskin_set1<-diary_activities [which(diary_activities$Setting == "1"),]
adiaryskin_set2<-diary_activities [which(diary_activities$Setting == "2"),]
adiaryair_set1<-diary_activities [which(diary_activities$Setting == "1"),]
adiaryair_set2<-diary_activities [which(diary_activities$Setting == "2"),]

# in order to merge the diary to the four different datasets that we will create (one for peaks one for troughs in each setting)
# we create a new variable Code_order by merging the ID col with Setting variables and seperate them 
#by 'S-' for skin data 
adiaryskin_set1$Code_order <- paste(adiaryskin_set1$ID, adiaryskin_set1$Setting, sep = "-S")                 
adiaryskin_set2$Code_order <- paste(adiaryskin_set2$ID, adiaryskin_set2$Setting, sep = "-S")         
adiaryair_set1$Code_order <- paste(adiaryair_set1$ID, adiaryair_set1$Setting, sep = "-A")                 
adiaryair_set2$Code_order <- paste(adiaryair_set2$ID, adiaryair_set2$Setting, sep = "-A")         

#removing the two first columns (ID, Setting) 
adiaryair_set1<-select (adiaryair_set1, -c(ID, Setting))
adiaryair_set2<-select (adiaryair_set2, -c(ID, Setting))
adiaryskin_set1<-select (adiaryskin_set1, -c(ID, Setting))
adiaryskin_set2<-select (adiaryskin_set2, -c(ID, Setting))

rm(diary_1,diary_2,diary_activities_1,diary_activities_2)

```

```{r}
######### PEAKS/TROUGHS FOR AIR TEMP ##########

#we create the plots of the smoothed line of each participants'data 

plots_func <- function(data,Code_order,threshold){
  x <- data[which(data$Code_order == Code_order),]
  x$Index1<-1:nrow(x)
  loessMod5 <- loess(x$Temperature~Index1, data=x, span=0.1) # 10% smoothing span
  x$smoothed5 <- predict(loessMod5) 
  
  pp <- findpeaks (x$smoothed5, nups = 1, ndowns = 0, minpeakheight = 0, minpeakdistance = 1, threshold = threshold, npeaks = 0, sortstr = FALSE)
  plot(x$smoothed5, type = 'l',main=paste("Peaks and troughs of ",Code_order, "with threshold", threshold),ylab="Temperature",xlab="Date")
  points(pp[,2],x$smoothed5[pp[,2]], col = 'red', pch = 19)
}  

co_list <- c( "T10-A1", "T11-A1", "T15-A1", "T24-A1", "T29-A1", 
              "T33-A1", "T38-A1", "T45-A1", "T53-A1", "T60-A1")
for(i in co_list){
  for(j in seq(0.1,0.7,0.1)){
    plots_func(data_air,i,j)
  }
}
```

```{r}
co_list_skin <- c( "T10-S1", "T11-S1", "T16-S2", "T24-S1", "T29-S1", 
              "T33-S2", "T34-S2", "T45-S1", "T56-S1", "T60-S2")
for(i in co_list_skin){
  for(j in seq(0.1,0.7,0.1)){
    plots_func(data_skin,i,j)
  }
}
```
